name: k8s image sync
description: An action for syncing kubernetes gcr.io images
branding: 
  color: blue
  icon: code
inputs:
  username:
    description: 'Username used to login docker registry'
    required: true
  password:
    description: 'Password used to login docker registry'
    required: true
  registry:
    description: 'Docker registry server address'
    required: false
    default: ''
  owner:
    description: 'docker image owner name'
    required: true
  kubernetes_version:
    description: 'set kubernetes version'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
